In [1]:
import numpy as np

In [2]:
with open('POSCAR_carte.vasp', 'r') as data:
    file = data.readlines()

In [3]:
print(file)

['"Se1 Ag1 I2 Cu1 S1"\n', '1.0\n', '        3.8594527245         0.0000000000         0.0000000000\n', '       -1.9461213380         4.5835289618         0.0000000000\n', '        0.0000000000         0.0000000000        21.6476936340\n', '   Se   Ag    I   Cu    S\n', '    1    1    2    1    1\n', 'Cartesian\n', '    -0.024200738         3.594885940        10.578389880\n', '     1.907480793         3.140505257         8.756403209\n', '    -0.017437965         1.468261065         7.499697032\n', '     1.902610462         2.839461957        14.142503782\n', '    -0.023002148         1.805596476        12.612436573\n', '     1.910933486         0.972965871        11.510610636\n']


In [4]:
lm = np.array([list(map(float, file[2:5][i].split())) for i in range(len(file[2:5]))]).T

In [5]:
lm

array([[ 3.85945272, -1.94612134,  0.        ],
       [ 0.        ,  4.58352896,  0.        ],
       [ 0.        ,  0.        , 21.64769363]])

In [6]:
a1 = np.array([1, 0, 0])

In [7]:
b1 = np.dot(np.linalg.inv(lm), a1).T

In [8]:
b1

array([0.25910409, 0.        , 0.        ])

In [9]:
lm2 = np.array([list(map(float, file[2:5][i].split())) for i in range(len(file[2:5]))])

In [10]:
lm2

array([[ 3.85945272,  0.        ,  0.        ],
       [-1.94612134,  4.58352896,  0.        ],
       [ 0.        ,  0.        , 21.64769363]])

In [11]:
b2 = np.dot(np.linalg.inv(lm2), a1)

In [12]:
b2

array([0.25910409, 0.11001305, 0.        ])

In [13]:
carte_coord_matrix = np.array([list(map(float, j.split()[:3])) for j in file[8:]]).T

In [14]:
carte_coord_matrix

array([[-0.02420074,  1.90748079, -0.01743796,  1.90261046, -0.02300215,
         1.91093349],
       [ 3.59488594,  3.14050526,  1.46826107,  2.83946196,  1.80559648,
         0.97296587],
       [10.57838988,  8.75640321,  7.49969703, 14.14250378, 12.61243657,
        11.51061064]])

In [15]:
carte_coord_matrix[2]

array([10.57838988,  8.75640321,  7.49969703, 14.14250378, 12.61243657,
       11.51061064])

In [16]:
max(carte_coord_matrix[2])

14.142503782

In [17]:
min(carte_coord_matrix[2])

7.499697032

In [18]:
max(carte_coord_matrix[2])-min(carte_coord_matrix[2])

6.64280675

In [19]:
def slab_width(str_file):
    with open(str_file, 'r') as data:
        fl = data.readlines()
        
        Coord_mat = np.array([list(map(float, fl[8:][i].split())) for i in range(len(fl[8:]))]).T
    
        axis=input("Enter the axis of non-periodicity\n")
    
    
        if axis=="X" or axis=="x":
            n=0
        elif axis=="Y" or axis=="y":
            n=1
        elif axis=="Z" or axis=="z":
            n=2
        else:
            print("Type error")
            
        surface_width = max(Coord_mat[n]) - min(Coord_mat[n])
    
    return surface_width
    

In [20]:
slab_width("POSCAR_carte.vasp")

Enter the axis of non-periodicity
 z


6.64280675

In [21]:
A = np.array([1, 2, 3])
B = np.array([3, 2, 1])

In [22]:
print(A)

[1 2 3]


In [23]:
np.inner(A, B)

10

In [24]:
np.inner(B, A)

10

In [25]:
np.outer(A, B)

array([[3, 2, 1],
       [6, 4, 2],
       [9, 6, 3]])

In [26]:
np.outer(B, A)

array([[3, 6, 9],
       [2, 4, 6],
       [1, 2, 3]])