#### Lattice vectors $a_1, a_2, a_3$ are the lattice vectors (basis vectors in the real/direct space) for the crystal. Where $a_n = a_{nx}\hat{i} + a_{ny}\hat{j} + a_{nz}\hat{k}$ and $\hat{i} = \begin{bmatrix} 1 \\ 0 \\ 0\end{bmatrix}, \hat{j} = \begin{bmatrix} 0 \\ 1 \\ 0\end{bmatrix}, \hat{k} = \begin{bmatrix} 0 \\ 0 \\ 1\end{bmatrix}$ are unit vectors in cartesian coordinate. 
#### So the transformation matrix for the crystal to its cartesian coordinate is $A = \begin{bmatrix} a_1 \ a_2 \ a_3\end{bmatrix}$. 
#### In the POSCAR file $a_is$ are arranged vertically, so I have taken the transpose of the array to get the transformation matrix (named lattice_matrix). 
#### Let $\vec{C_1}$ is a vector (represented by the cartesian coordinate of an atom) in the cartesian space is represented by $\vec{F_1}$ in direct space (represented by the fractional coordinate of that atom).

#### $\vec{C_1} = \begin{bmatrix} C_{1a1} \\ C_{1a2} \\ C_{1a3}\end{bmatrix} = C_{1a1}a_1 + C_{1a2}a_2 + C_{1a3}a_3$
#### and 
#### $\vec{F_1} = \begin{bmatrix} F_{1b1} \\ F_{1b2} \\ F_{1b3}\end{bmatrix} = F_{1b1}b_1 + F_{1b2}b_2 + F_{1b3}b_3$, where $b_1, b_2, b_3$ are basis vectors in the direct space

#### Then cartesian coordinate can be achieved from the fractional coordinate by $\vec{C_1} = A\vec{F_1}$
#### and fractional coordinate can be achieved from the cartesian coordinate by $\vec{F_1} = B\vec{C_1}$,
#### where $B = \begin{bmatrix} b_1 \ b_2 \ b_3\end{bmatrix}$ is the transformation matrix to the direct space.
#### Alternatively, $\vec{F_1} = A^{-1}\vec{C_1}$, therefore, $B = A^{-1}$. 
#### For a system with more than one atom, the matrix for the coordinates of the atoms is generated by putting each vector column-wise as $C = \begin{bmatrix} C_1 \ C_2 \ ...\end{bmatrix}$ or $F = \begin{bmatrix} F_1 \ F_2 \ ...\end{bmatrix}$

#### In the POSCAR file $C_is$ or $F_is$ are arranged vertically. So to get the coordinate matrices ($C$ or $F$) I have taken the transpose of the arrays.

In [1]:
import numpy as np

In [2]:
#def 

In [3]:
with open('POSCAR_carte.vasp', 'r') as data:
    file = data.readlines()

In [4]:
print(file)

['K5CuSb2                                 \n', '1.0\n', '        9.9642868042         0.0000000000         0.0000000000\n', '        8.1907009722         5.6744540795         0.0000000000\n', '        8.1907009722         2.5600544114         5.0641436108\n', '    K   Cu   Sb\n', '    5    1    2\n', 'Cartesian\n', '    13.172844374         4.117254245         2.532071805\n', '    16.742525391         5.232980197         3.218232546\n', '     9.603164143         3.001528540         1.845911215\n', '    20.599742414         6.438577311         3.959663189\n', '     5.745946335         1.795931180         1.104480422\n', '     0.000000000         0.000000000         0.000000000\n', '    24.004008491         7.502601797         4.614028025\n', '     2.341680454         0.731906756         0.450115623\n']


In [5]:
#lm = list(map(float, list(file[i] for i in file[2:5]))

In [6]:
print(file[2].split())

['9.9642868042', '0.0000000000', '0.0000000000']


In [7]:
list(map(float, file[2].split()))

[9.9642868042, 0.0, 0.0]

In [8]:
print(file[2:5])

['        9.9642868042         0.0000000000         0.0000000000\n', '        8.1907009722         5.6744540795         0.0000000000\n', '        8.1907009722         2.5600544114         5.0641436108\n']


In [9]:
lm = np.array([list(map(float, file[2:5][i].split())) for i in range(len(file[2:5]))]).T

In [10]:
print(lm)

[[9.9642868  8.19070097 8.19070097]
 [0.         5.67445408 2.56005441]
 [0.         0.         5.06414361]]


In [11]:
np.sqrt(lm[0][0]**2 + lm[1][0]**2 + lm[2][0]**2)

9.9642868042

In [12]:
np.sqrt(lm[0][1]**2 + lm[1][1]**2 + lm[2][1]**2)

9.964286804199899

In [13]:
np.sqrt(lm[0][2]**2 + lm[1][2]**2 + lm[2][2]**2)

9.964286804188903

In [14]:
print(np.linalg.inv(lm))

[[ 0.10035841 -0.14486076 -0.08908798]
 [ 0.          0.17622841 -0.08908798]
 [ 0.          0.          0.19746675]]


In [15]:
C = np.array([list(map(float, file[8:][i].split())) for i in range(len(file[8:]))]).T

In [16]:
print(C)

[[13.17284437 16.74252539  9.60316414 20.59974241  5.74594634  0.
  24.00400849  2.34168045]
 [ 4.11725424  5.2329802   3.00152854  6.43857731  1.79593118  0.
   7.5026018   0.73190676]
 [ 2.53207181  3.21823255  1.84591122  3.95966319  1.10448042  0.
   4.61402802  0.45011562]]


In [17]:
np.sqrt(C[0][2]**2 + C[1][2]**2 + C[2][2]**2)

10.22923864945472

In [18]:
F = np.dot(np.linalg.inv(lm), C).T

In [19]:
print(F)

[[0.5        0.5        0.5       ]
 [0.63549393 0.63549393 0.63549393]
 [0.3645061  0.3645061  0.3645061 ]
 [0.78190184 0.78190184 0.78190184]
 [0.21809816 0.21809816 0.21809816]
 [0.         0.         0.        ]
 [0.91111714 0.91111714 0.91111714]
 [0.08888287 0.08888287 0.08888287]]


In [20]:
# def carte_to_frac(str_file):
#     with open(str_file, 'r') as data:
#         file = data.readlines()
        
#         lattice_matrix = np.array([list(map(float, file[2:5][i].split())) for i in range(len(file[2:5]))]).T
#         carte_coord_matrix = np.array([list(map(float, file[8:][i].split())) for i in range(len(file[8:]))]).T
#         fractional_coord = np.dot(np.linalg.inv(lattice_matrix), carte_coord_matrix).T
        
#     return fractional_coord

In [21]:
# carte_to_frac('POSCAR_carte.vasp')

In [22]:
# def carte_to_frac(str_file):
#     with open(str_file, 'r') as data:
#         file = data.readlines()
        
#         lattice_matrix = np.array([list(map(float, file[2:5][i].split())) for i in range(len(file[2:5]))]).T
#         carte_coord_matrix = np.array([list(map(float, file[8:][i].split())) for i in range(len(file[8:]))]).T
#         fractional_coord = np.dot(np.linalg.inv(lattice_matrix), carte_coord_matrix).T
    

#     for i in fractional_coord:
#         print(i[0], '\t', i[1], '\t', i[2])

In [23]:
# carte_to_frac('POSCAR_carte.vasp')

In [24]:
def carte_to_frac(str_file):
    with open(str_file, 'r') as data:
        fl = data.readlines()
        
        scale_factor = float(fl[1])
        lattice_matrix = scale_factor*np.array([list(map(float, i.split())) for i in fl[2:5]]).T
        carte_coord_matrix = np.array([list(map(float, j.split()[:3])) for j in fl[8:]]).T
        fractional_coord = np.dot(np.linalg.inv(lattice_matrix), carte_coord_matrix).T
    
    with open('poscar_frac.vasp', 'w') as output:
        output.write('generated by sampad' +'\n')
        for k in fl[1:7]:
            output.write(k)
        # output.write(str(scale_factor)+'\n')
        # output.write(fl[2])
        # output.write(fl[3])
        # output.write(fl[4])
        # output.write(fl[5])
        # output.write(fl[6])
        
        output.write('Direct'+'\n')       
        for l in fractional_coord:
            output.write('\t'+str(l[0])+'\t'+str(l[1])+'\t'+str(l[2])+'\n')
            # output.write('\t'+str(i[1])+'\t')
            # output.write('\t'+str(i[2])+'\n')
    return fractional_coord

In [25]:
carte_to_frac('POSCAR_carte.vasp')

array([[0.5       , 0.5       , 0.5       ],
       [0.63549393, 0.63549393, 0.63549393],
       [0.3645061 , 0.3645061 , 0.3645061 ],
       [0.78190184, 0.78190184, 0.78190184],
       [0.21809816, 0.21809816, 0.21809816],
       [0.        , 0.        , 0.        ],
       [0.91111714, 0.91111714, 0.91111714],
       [0.08888287, 0.08888287, 0.08888287]])

In [26]:
def carte_to_frac(str_file):
    with open(str_file, 'r') as data:
        fl = data.readlines()
        
        scale_factor = float(fl[1])
        
        lattice_matrix = scale_factor*np.array([list(map(float, i.split())) for i in fl[2:5]]).T
        carte_coord_matrix = np.array([list(map(float, j.split())) for j in fl[8:]]).T
        fractional_coord = np.dot(np.linalg.inv(lattice_matrix), carte_coord_matrix).T
    
    with open('poscar_frac.vasp', 'w') as output:
        output.write("generated by sampad's python code" +'\n')
        # for k in fl[1:7]:
        #     output.write(k)
        output.writelines(fl[1:7])    
            

        output.write('Direct'+'\n')
        for l in fractional_coord:
            output.write('\t'+"{:.16f}".format(l[0])+'\t'+"{:.16f}".format(l[1])+'\t'+"{:.16f}".format(l[2])+'\n')

    return fractional_coord

In [27]:
carte_to_frac('POSCAR_carte.vasp')

array([[0.5       , 0.5       , 0.5       ],
       [0.63549393, 0.63549393, 0.63549393],
       [0.3645061 , 0.3645061 , 0.3645061 ],
       [0.78190184, 0.78190184, 0.78190184],
       [0.21809816, 0.21809816, 0.21809816],
       [0.        , 0.        , 0.        ],
       [0.91111714, 0.91111714, 0.91111714],
       [0.08888287, 0.08888287, 0.08888287]])