#### Lattice vectors $a_1, a_2, a_3$ are the lattice vectors (basis vectors in the direct/real space) regarding cartesian coordinates. Where $a_n = a_{nx}\hat{i} + a_{ny}\hat{j} + a_{nz}\hat{k}$ and $\hat{i} = \begin{bmatrix} 1 \\ 0 \\ 0\end{bmatrix}, \hat{j} = \begin{bmatrix} 0 \\ 1 \\ 0\end{bmatrix}, \hat{k} = \begin{bmatrix} 0 \\ 0 \\ 1\end{bmatrix}$ are unit vectors in cartesian coordinate. 
#### So the transformation matrix for the crystal to its cartesian coordinate is $A = \begin{bmatrix} a_1 \ a_2 \ a_3\end{bmatrix}$. 
#### In the POSCAR file $a_is$ are arranged vertically, so I have taken the transpose of the array to get the transformation matrix (named lattice_matrix). 
#### Let $\vec{C_1}$ is a vector (represented by the cartesian coordinate of an atom) in the cartesian space is represented by $\vec{F_1}$ in direct space (represented by the direct coordinate of that atom).

#### $\vec{C_1} = \begin{bmatrix} C_{1a1} \\ C_{1a2} \\ C_{1a3}\end{bmatrix} = C_{1a1}a_1 + C_{1a2}a_2 + C_{1a3}a_3$
#### and 
#### $\vec{F_1} = \begin{bmatrix} F_{1b1} \\ F_{1b2} \\ F_{1b3}\end{bmatrix} = F_{1b1}b_1 + F_{1b2}b_2 + F_{1b3}b_3$, where $b_1, b_2, b_3$ are basis vectors in the direct space in terms of fractional coordinates

#### Then cartesian coordinate can be achieved from the fractional coordinate by $\vec{C_1} = A\vec{F_1}$
#### and fractional coordinate can be achieved from the cartesian coordinate by $\vec{F_1} = B\vec{C_1}$,
#### where $B = \begin{bmatrix} b_1 \ b_2 \ b_3\end{bmatrix}$ is the transformation matrix to the direct space.
#### Alternatively, $\vec{F_1} = A^{-1}\vec{C_1}$, therefore, $B = A^{-1}$. 
#### For a system with more than one atom, the matrix for the coordinates of the atoms is generated by putting each vector column-wise as $C = \begin{bmatrix} C_1 \ C_2 \ ...\end{bmatrix}$ or $F = \begin{bmatrix} F_1 \ F_2 \ ...\end{bmatrix}$

#### In the POSCAR file $C_is$ or $F_is$ are arranged vertically. So to get the coordinate matrices ($C$ or $F$) I have taken the transpose of the arrays.

In [1]:
import numpy as np

In [2]:
with open('POSCAR_unitcell', 'r') as data:
    file = data.readlines()

In [3]:
print(file)

['K5CuSb2\n', '   1.00000000000000     \n', '     9.9642821371889738   -0.0078303211631481   -0.0048139447635795\n', '     8.1951566441023420    5.6680144143786944   -0.0048139447636245\n', '     8.1951566441022692    2.5543793416265430    5.0597980943421703\n', '   K    Cu   Sb\n', '   5     1    2\n', 'Direct\n', '  0.5000000000000000  0.5000000000000000  0.5000000000000000\n', '  0.6354939155472525  0.6354939155472525  0.6354939155472525\n', '  0.3645060844527478  0.3645060844527478  0.3645060844527478\n', '  0.7819018364271487  0.7819018364271487  0.7819018364271487\n', '  0.2180981635728510  0.2180981635728510  0.2180981635728510\n', '  0.0000000000000000  0.0000000000000000 -0.0000000000000000\n', '  0.9111171097102632  0.9111171097102631  0.9111171097102632\n', '  0.0888828682897351  0.0888828682897351  0.0888828682897351\n']


In [4]:
lm = np.array([list(map(float, file[2:5][i].split())) for i in range(len(file[2:5]))]).T

In [5]:
F = np.array([list(map(float, file[8:][i].split()[:3])) for i in range(len(file[8:]))]).T

In [6]:
print(F)

[[ 0.5         0.63549392  0.36450608  0.78190184  0.21809816  0.
   0.91111711  0.08888287]
 [ 0.5         0.63549392  0.36450608  0.78190184  0.21809816  0.
   0.91111711  0.08888287]
 [ 0.5         0.63549392  0.36450608  0.78190184  0.21809816 -0.
   0.91111711  0.08888287]]


In [7]:
C = np.dot(lm, F).T

In [8]:
print(C)

[[13.17729771  4.10728172  2.5250851 ]
 [16.74818504  5.22030508  3.20935244]
 [ 9.60641039  2.99425835  1.84081777]
 [20.60670656  6.42298224  3.94873736]
 [ 5.74788886  1.7915812   1.10143285]
 [ 0.          0.          0.        ]
 [24.01212281  7.48442929  4.60129648]
 [ 2.34247203  0.73013396  0.44887361]]


In [9]:
def direct_to_carte(str_file):
    with open(str_file, 'r') as data:
        fl = data.readlines()
        
        scale_factor = float(fl[1])
        
        lattice_matrix = scale_factor*np.array([list(map(float, i.split())) for i in fl[2:5]]).T
        frac_coord_matrix = np.array([list(map(float, j.split()[:3])) for j in fl[8:]]).T
        carte_coord = np.dot(lattice_matrix, frac_coord_matrix).T
    
    with open('poscar_carte.vasp', 'w') as output:
        output.write("generated by sampad's python code" +'\n')
        # for k in fl[1:7]:
        #     output.write(k)
        output.writelines(fl[1:7])
            

        output.write('Cartesian'+'\n')
        for l in carte_coord:
            output.write('\t'+"{:.16f}".format(l[0])+'\t'+"{:.16f}".format(l[1])+'\t'+"{:.16f}".format(l[2])+'\n')

    return carte_coord

In [10]:
direct_to_carte('POSCAR_unitcell')

array([[13.17729771,  4.10728172,  2.5250851 ],
       [16.74818504,  5.22030508,  3.20935244],
       [ 9.60641039,  2.99425835,  1.84081777],
       [20.60670656,  6.42298224,  3.94873736],
       [ 5.74788886,  1.7915812 ,  1.10143285],
       [ 0.        ,  0.        ,  0.        ],
       [24.01212281,  7.48442929,  4.60129648],
       [ 2.34247203,  0.73013396,  0.44887361]])