In [1]:
import numpy as np

In [2]:
with open('POSCAR', 'r') as data:
    file = data.readlines()

In [3]:
print(file)

['K4ZnAs2                                 \n', '1.0\n', '        9.5081825256         0.0000000000         0.0000000000\n', '        7.7694339556         5.4810063811         0.0000000000\n', '        7.7694339556         2.4647101720         4.8955729714\n', '    K   Zn   As\n', '    4    1    2\n', 'Cartesian\n', '     9.669735938         3.067546061         1.889998905\n', '     5.246399728         1.664323920         1.025435421\n', '    19.800651455         6.281392870         3.870137696\n', '    15.377314498         4.878170492         3.005574066\n', '     0.000000000         0.000000000         0.000000000\n', '     2.165499537         0.686964941         0.423257861\n', '    22.881551273         7.258751731         4.472315183\n']


In [4]:
lm = np.array([list(map(float, file[2:5][i].split())) for i in range(len(file[2:5]))]).T

In [5]:
lm

array([[9.50818253, 7.76943396, 7.76943396],
       [0.        , 5.48100638, 2.46471017],
       [0.        , 0.        , 4.89557297]])

In [21]:
file[5:7]

['    K   Zn   As\n', '    4    1    2\n']

In [24]:
list(file[5].split())

['K', 'Zn', 'As']

In [31]:
elements = list(file[5].split())

In [84]:
list(elements)

['K', 'Zn', 'As']

In [83]:
elements.index("Zn")

1

In [95]:
element_num = zip(list(file[5].split()), list(map(int, file[6].split())))

In [57]:
for (element, num) in element_num:
    print(num)

4
1
2


In [60]:
for i, (element, num) in enumerate(element_num):
    print(i, num)

0 4
1 1
2 2


In [81]:
s = 0
l = [0]
for i, (element, num) in enumerate(element_num):
    s = s + num
    l = l+[s]
    print(s)
print(l)

4
5
7
[0, 4, 5, 7]


In [52]:
list(element_num)

[('K', 4), ('Zn', 1), ('As', 2)]

In [47]:
list(range(0+4+1, (0+4+1)+2, 1))

[5, 6]

In [97]:
def element_pos(ele):
    n = elements.index(ele)
    
    s = 0
    l = [0]
    for num in list(map(int, file[6].split())):
        s = s + num
        l = l+[s]

    start = l[n]
    stop = l[n+1]
    return list(range(start, stop, 1))

In [101]:
element_pos("As")

[5, 6]

In [132]:
carte_coord_matrix = np.array([list(map(float, j.split()[:3])) for j in file[8:]]).T

In [133]:
carte_coord_matrix

array([[ 9.66973594,  5.24639973, 19.80065146, 15.3773145 ,  0.        ,
         2.16549954, 22.88155127],
       [ 3.06754606,  1.66432392,  6.28139287,  4.87817049,  0.        ,
         0.68696494,  7.25875173],
       [ 1.8899989 ,  1.02543542,  3.8701377 ,  3.00557407,  0.        ,
         0.42325786,  4.47231518]])

In [134]:
carte_coord_matrix[2][0] = carte_coord_matrix[2][0] - 0.06

In [135]:
carte_coord_matrix

array([[ 9.66973594,  5.24639973, 19.80065146, 15.3773145 ,  0.        ,
         2.16549954, 22.88155127],
       [ 3.06754606,  1.66432392,  6.28139287,  4.87817049,  0.        ,
         0.68696494,  7.25875173],
       [ 1.8299989 ,  1.02543542,  3.8701377 ,  3.00557407,  0.        ,
         0.42325786,  4.47231518]])

In [16]:
max(carte_coord_matrix[2])

4.472315183

In [17]:
min(carte_coord_matrix[2])

0.0

In [18]:
max(carte_coord_matrix[2])-min(carte_coord_matrix[2])

4.472315183

In [168]:
def at_disp(str_file):
    with open(str_file, 'r') as data:
        fl = data.readlines()
        
        scale_factor = float(fl[1])
        lattice_vectors = scale_factor*np.array([list(map(float, i.split())) for i in fl[2:5]])
        
        Coord_mat = np.array([list(map(float, fl[8:][i].split())) for i in range(len(fl[8:]))]).T
        
        elements = list(fl[5].split())
        
        ele = input("Enter the element\n")
        axis = input("Enter the axis\n")
        
        def element_pos(ele):
            n = elements.index(ele)
    
            s = 0
            l = [0]
            for num in list(map(int, fl[6].split())):
                s = s + num
                l = l+[s]

            start = l[n]
            stop = l[n+1]
            return list(range(start, stop, 1))
        
        if axis == "X":
            c = 0
        elif axis == "Y":
            c = 1
        elif axis == "Z":
            c = 2
        else:
            print("Type error")
        for disp in [-0.06, -0.05, -0.04, -0.03, -0.02, -0.01, 0.00, 
                     +0.01, +0.02, +0.03, +0.04, +0.05, +0.06]:
            new_Coord_mat = Coord_mat.copy()
            for p in element_pos(ele):
                new_Coord_mat[c][p] = new_Coord_mat[c][p] + disp
            new_Coord = new_Coord_mat.T
            # print(new_Coord)

                
                

            with open('POSCAR_'+str(disp), 'w') as output:
                output.write("generated by sampad's python code" +'\n')
                output.write("1.0" + '\n')
            
                for lv in lattice_vectors:
                    output.write('\t'+"{:.16f}".format(lv[0])+'\t'+"{:.16f}".format(lv[1])+
                                    '\t'+"{:.16f}".format(lv[2])+'\n')
                
                output.writelines(fl[5:8])
                for nc in new_Coord:
                    output.write('\t'+"{:.16f}".format(nc[0])+'\t'+"{:.16f}".format(nc[1])+
                                 '\t'+"{:.16f}".format(nc[2])+'\n')
        

In [167]:
at_disp("POSCAR")

Enter the element
 K
Enter the axis
 Z


In [136]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [137]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [153]:
b = a.copy()

In [154]:
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [155]:
for x in range(5,10,1):
    b[1][1] = a.copy()[1][1] + x
    print(b)

[[ 1  2  3]
 [ 4 10  6]
 [ 7  8  9]]
[[ 1  2  3]
 [ 4 11  6]
 [ 7  8  9]]
[[ 1  2  3]
 [ 4 12  6]
 [ 7  8  9]]
[[ 1  2  3]
 [ 4 13  6]
 [ 7  8  9]]
[[ 1  2  3]
 [ 4 14  6]
 [ 7  8  9]]


In [148]:
b

array([[ 1,  2,  3],
       [ 4, 45,  6],
       [ 7,  8,  9]])

In [142]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])